### PR TITLE
Fix link.

### PR DESCRIPTION
**Pull request by safetytrick**

### CODE REVIEW

**Comment by artembilan** [comment]
Hello @safetytrick !

Even for such a simple fix we must be sure that you have signed the CLA: https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.md

Thank you very much for contribution!

**Comment by safetytrick** [comment]
I have signed and agree to the terms of the SpringSource Individual
Contributor License Agreement.

**Comment by safetytrick** [comment]
:+1:

**Comment by garyrussell** [comment]
Merged as 2201dbc19c179f7cd863f228372ff10828f969c3 after minor commit comment polishing.

@safetytrick - thanks for the contribution.

**Pull request closed without merging**
