### PR TITLE
Rename `reconnectInterval` to `recoveryInterval`

### PR DESCRIPTION
**Pull request by mbogoevici**

### CODE REVIEW

**Comment by garyrussell** [comment]
Do we really want to make a breaking API change in a point release?

**Comment by artembilan** [comment]
@garyrussell , it's not breaking change. Just see the previous commit in `master`. And pay attention to the `@since` on the setter.
That just was my fault do not think here about API alignment with Spring AMQP...

**Comment by artembilan** [comment]
Sorry, not `master` - `1.3.x`

**Comment by garyrussell** [comment]
Oops - got it; thanks 😄

**Comment by mbogoevici** [comment]
Yeah, sorry - I should have made that clearer in the commit message :)

**Pull request merged**
